version: '3.1'

services:

  mysqldb:  

    image: mysql:5.7

    restart: always

    container_name: mysql

    volumes:

      - ./mysql-volume:/var/lib/mysql

    environment:

      MYSQL_ROOT_PASSWORD: root

      MYSQL_DATABASE: db

      MYSQL_USER: blog-user

      MYSQL_PASSWORD: supersecret

  ghost:

    build: ./ghost
    image: lvthillo/ghost:1.20.0

    container_name: ghost

    volumes:

      - ./ghost-volume:/var/lib/ghost/content

    restart: always

    environment:

      database__client: mysql

      database__connection__host: mysql

      database__connection__user: blog-user

      database__connection__password: supersecret

      database__connection__database: db

    depends_on:

      - mysqldb

    entrypoint: ["wait-for-it.sh", "mysql", "--", "docker-entrypoint.sh"]

    command: ["node", "current/index.js"]

  nginx:
    
    build: ./nginx
    container_name: nginx    

    restart: always
    
    depends_on:
      - ghost
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - /etc/selfsign/:/etc/selfsign/
       - ./nginx_volume:/usr/share/nginx/html
